spring:
  application:
    name: DiceJobSearch
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    mcp:
      client:
        streamable-http:
          connections:
            dice-server:
              url: https://mcp.dice.com
              endpoint: /mcp
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
server:
  port: 8080
  servlet:
    context-path: /jobsearch

jobsearch:
  default-query: "I am looking for a java software developer position. It must be in Huntsville, AL OR remote. Positions
   that are in  must not require active security clearance or active top secret security clearance in order to apply.
   Positions in Huntsville may be onsite or hybrid or remote. Positions that are not in Huntsville must be fully remote. 
   The position will require experience any of  java, spring boot, postgreSQL. It may contain Angular, it may contain 
   Angular and React but it will not include React without the presence of Angular. W2 Contract work is preferred, 
   full-time and part-time work are acceptable. "
  runner:
    enabled: false

